user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;

    keepalive_timeout  65;


    gzip on;                          # 开启 Gzip
    gzip_static on;     # 启用静态 Gzip 文件支持
    gzip_comp_level 6;                # 设置压缩级别，推荐值为 5，兼顾性能和压缩率
    gzip_types                        # 启用压缩的 MIME 类型
        text/plain
        text/css
        application/json
        application/javascript
        text/xml
        application/xml
        application/xml+rss
        text/javascript
        image/svg+xml;
    gzip_min_length 1024;             # 不压缩小于 1KB 的内容
    gzip_vary on;                     # 添加 `Vary: Accept-Encoding` 响应头，适配代理缓存
    gzip_proxied any;                 # 对任何代理请求启用压缩
    gzip_disable "msie6";             # 禁用对 IE6 的压缩（兼容性问题）

    # 缓冲区配置（可选，默认即可）
    gzip_buffers 16 8k;


    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;
    
        location / {
            root   /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
            index  index.html index.htm;
        }
    
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}